
services:
  dianfe_app:
    image: ddg066/dianfe:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: dianfe
    network_mode: "bridge"
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
    # volumes:
    #   - ./:/data        # if you want to read homeassistant.db, homeassistant.db is in the container at /data/
    command: python3 main.py
    init: true
