name: Docker Image Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version of this branch'
        default: 'v1.26'
        required: true
        type: string

    paths:
      - 'scripts/**'
      - 'Dockerfile-for-github-action'
      - 'requirements.txt'
      - '.env'
      - '.github/workflows/docker-image.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log into Docker Hub registry
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    
    - name: Build and push Docker image
      run: |
        PLATFORMS=linux/arm64,linux/amd64
        DOCKER_IMAGE=ddg066/dianfe
        ARCH_TAGS="arm64 amd64"
        VERSION=${{ inputs.version }}
        
        docker buildx build --build-arg VERSION=${VERSION} --platform $PLATFORMS -t $DOCKER_IMAGE:latest -t $DOCKER_IMAGE:${VERSION} --file Dockerfile-for-github-action --push .
        
        for ARCH in $ARCH_TAGS; do
          if [ "$ARCH" == "arm64" ]; then
            TAG_ARCH="aarch64"
          else
            TAG_ARCH=$ARCH
          fi
          docker buildx build --build-arg VERSION=${VERSION} --platform linux/${ARCH} -t ${DOCKER_IMAGE}-${TAG_ARCH}:latest -t ${DOCKER_IMAGE}-${TAG_ARCH}:${VERSION} --file Dockerfile-for-github-action --push .
        done
    - name: Delete old workflow runs
      uses: mattraks/delete-workflow-runs@v2
      with:
        token: ${{ secrets.PAT_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 0
